<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            [ "name" => "Afghanistan", "iso_code" => "AF" ],
            [ "name" => "Albania", "iso_code" => "AL" ],
            [ "name" => "Algeria", "iso_code" => "DZ" ],
            [ "name" => "Andorra", "iso_code" => "AD" ],
            [ "name" => "Angola", "iso_code" => "AO" ],
            [ "name" => "Argentina", "iso_code" => "AR" ],
            [ "name" => "Armenia", "iso_code" => "AM" ],
            [ "name" => "Australia", "iso_code" => "AU" ],
            [ "name" => "Austria", "iso_code" => "AT" ],
            [ "name" => "Azerbaijan", "iso_code" => "AZ" ],
            [ "name" => "Bahamas", "iso_code" => "BS" ],
            [ "name" => "Bahrain", "iso_code" => "BH" ],
            [ "name" => "Bangladesh", "iso_code" => "BD" ],
            [ "name" => "Barbados", "iso_code" => "BB" ],
            [ "name" => "Belarus", "iso_code" => "BY" ],
            [ "name" => "Belgium", "iso_code" => "BE" ],
            [ "name" => "Belize", "iso_code" => "BZ" ],
            [ "name" => "Benin", "iso_code" => "BJ" ],
            [ "name" => "Bhutan", "iso_code" => "BT" ],
            [ "name" => "Bolivia", "iso_code" => "BO" ],
            [ "name" => "Bosnia and erzegovina", "iso_code" => "BA" ],
            [ "name" => "Botswana", "iso_code" => "BW" ],
            [ "name" => "Brazil", "iso_code" => "BR" ],
            [ "name" => "Brunei", "iso_code" => "BN" ],
            [ "name" => "Bulgaria", "iso_code" => "BG" ],
            [ "name" => "Burkina Faso", "iso_code" =>  "BF" ],
            [ "name" => "Burundi", "iso_code" => "BI" ],
            [ "name" => "Cabo Verde", "iso_code" =>  "CV" ],
            [ "name" => "Cambodia", "iso_code" => "KH" ],
            [ "name" => "Cameroon", "iso_code" => "CM" ],
            [ "name" => "Canada", "iso_code" => "CA" ],
            [ "name" => "Central African epublic", "iso_code" => "CF" ],
            [ "name" => "Chad", "iso_code" => "TD" ],
            [ "name" => "Chile", "iso_code" => "CL" ],
            [ "name" => "China", "iso_code" => "CN" ],
            [ "name" => "Colombia", "iso_code" => "CO" ],
            [ "name" => "Comoros", "iso_code" => "KM" ],
            [ "name" => "Congo", "iso_code" => "CG" ],
            [ "name" => "Congo, Democratic epublic of the", "iso_code" => "CD" ],
            [ "name" => "Costa Rica", "iso_code" =>  "CR" ],
            [ "name" => "Croatia", "iso_code" => "HR" ],
            [ "name" => "Cuba", "iso_code" => "CU" ],
            [ "name" => "Cyprus", "iso_code" => "CY" ],
            [ "name" => "Czech Republic", "iso_code" => "CZ" ],
            [ "name" => "Denmark", "iso_code" => "DK" ],
            [ "name" => "Djibouti", "iso_code" => "DJ" ],
            [ "name" => "Dominica", "iso_code" => "DM" ],
            [ "name" => "Dominican Republic", "iso_code" => "DO" ],
            [ "name" => "Ecuador", "iso_code" => "EC" ],
            [ "name" => "Egypt", "iso_code" => "EG" ],
            [ "name" => "El Salvador", "iso_code" => "SV" ],
            [ "name" => "Equatorial Guinea", "iso_code" => "GQ" ],
            [ "name" => "Eritrea", "iso_code" => "ER" ],
            [ "name" => "Estonia", "iso_code" => "EE" ],
            [ "name" => "Eswatini", "iso_code" => "SZ" ],
            [ "name" => "Ethiopia", "iso_code" => "ET" ],
            [ "name" => "Fiji", "iso_code" => "FJ" ],
            [ "name" => "Finland", "iso_code" => "FI" ],
            [ "name" => "France", "iso_code" => "FR" ],
            [ "name" => "Gabon", "iso_code" => "GA" ],
            [ "name" => "Gambia", "iso_code" => "GM" ],
            [ "name" => "Georgia", "iso_code" => "GE" ],
            [ "name" => "Germany", "iso_code" => "DE" ],
            [ "name" => "Ghana", "iso_code" => "GH" ],
            [ "name" => "Greece", "iso_code" => "GR" ],
            [ "name" => "Grenada", "iso_code" => "GD" ],
            [ "name" => "Guatemala", "iso_code" => "GT" ],
            [ "name" => "Guinea", "iso_code" => "GN" ],
            [ "name" => "Guinea-Bissau", "iso_code" => "GW" ],
            [ "name" => "Guyana", "iso_code" => "GY" ],
            [ "name" => "Haiti", "iso_code" => "HT" ],
            [ "name" => "Honduras", "iso_code" => "HN" ],
            [ "name" => "Hungary", "iso_code" => "HU" ],
            [ "name" => "Iceland", "iso_code" => "IS" ],
            [ "name" => "India", "iso_code" => "IN" ],
            [ "name" => "Indonesia", "iso_code" => "ID" ],
            [ "name" => "Iran", "iso_code" => "IR" ],
            [ "name" => "Iraq", "iso_code" => "IQ" ],
            [ "name" => "Ireland", "iso_code" => "IE" ],
            [ "name" => "Israel", "iso_code" => "IL" ],
            [ "name" => "Italy", "iso_code" => "IT" ],
            [ "name" => "Jamaica", "iso_code" => "JM" ],
            [ "name" => "Japan", "iso_code" => "JP" ],
            [ "name" => "Jordan", "iso_code" => "JO" ],
            [ "name" => "Kazakhstan", "iso_code" => "KZ" ],
            [ "name" => "Kenya", "iso_code" => "KE" ],
            [ "name" => "Kiribati", "iso_code" => "KI" ],
            [ "name" => "Kuwait", "iso_code" => "KW" ],
            [ "name" => "Kyrgyzstan", "iso_code" => "KG" ],
            [ "name" => "Laos", "iso_code" => "LA" ],
            [ "name" => "Latvia", "iso_code" => "LV" ],
            [ "name" => "Lebanon", "iso_code" => "LB" ],
            [ "name" => "Lesotho", "iso_code" => "LS" ],
            [ "name" => "Liberia", "iso_code" => "LR" ],
            [ "name" => "Libya", "iso_code" => "LY" ],
            [ "name" => "Liechtenstein", "iso_code" => "LI" ],
            [ "name" => "Lithuania", "iso_code" => "LT" ],
            [ "name" => "Luxembourg", "iso_code" => "LU" ],
            [ "name" => "Madagascar", "iso_code" => "MG" ],
            [ "name" => "Malawi", "iso_code" => "MW" ],
            [ "name" => "Malaysia", "iso_code" => "MY" ],
            [ "name" => "Maldives", "iso_code" => "MV" ],
            [ "name" => "Mali", "iso_code" => "ML" ],
            [ "name" => "Malta", "iso_code" => "MT" ],
            [ "name" => "Marshall Islands", "iso_code" => "MH" ],
            [ "name" => "Mauritania", "iso_code" => "MR" ],
            [ "name" => "Mauritius", "iso_code" => "MU" ],
            [ "name" => "Mexico", "iso_code" => "MX" ],
            [ "name" => "Micronesia", "iso_code" => "FM" ],
            [ "name" => "Moldova", "iso_code" => "MD" ],
            [ "name" => "Monaco", "iso_code" => "MC" ],
            [ "name" => "Mongolia", "iso_code" => "MN" ],
            [ "name" => "Montenegro", "iso_code" => "ME" ],
            [ "name" => "Morocco", "iso_code" => "MA" ],
            [ "name" => "Mozambique", "iso_code" => "MZ" ],
            [ "name" => "Myanmar", "iso_code" => "MM" ],
            [ "name" => "Namibia", "iso_code" => "NA" ],
            [ "name" => "Nauru", "iso_code" => "NR" ],
            [ "name" => "Nepal", "iso_code" => "NP" ],
            [ "name" => "Netherlands", "iso_code" => "NL" ],
            [ "name" => "New Zealand", "iso_code" => "NZ" ],
            [ "name" => "Nicaragua", "iso_code" => "NI" ],
            [ "name" => "Niger", "iso_code" => "NE" ],
            [ "name" => "Nigeria", "iso_code" => "NG" ],
            [ "name" => "North Korea", "iso_code" => "KP" ],
            [ "name" => "North Macedonia", "iso_code" => "MK" ],
            [ "name" => "Norway", "iso_code" => "NO" ],
            [ "name" => "Oman", "iso_code" => "OM" ],
            [ "name" => "Pakistan", "iso_code" => "PK" ],
            [ "name" => "Palau", "iso_code" => "PW" ],
            [ "name" => "Palestine", "iso_code" => "PS" ],
            [ "name" => "Panama", "iso_code" => "PA" ],
            [ "name" => "Papua New  =>uinea", "iso_code" => "PG" ],
            [ "name" => "Paraguay", "iso_code" => "PY" ],
            [ "name" => "Peru", "iso_code" => "PE" ],
            [ "name" => "Philippines", "iso_code" => "PH" ],
            [ "name" => "Poland", "iso_code" => "PL" ],
            [ "name" => "Portugal", "iso_code" => "PT" ],
            [ "name" => "Qatar", "iso_code" => "QA" ],
            [ "name" => "Romania", "iso_code" => "RO" ],
            [ "name" => "Russia", "iso_code" => "RU" ],
            [ "name" => "Rwanda", "iso_code" => "RW" ],
            [ "name" => "Saint Kittsnd Nevis", "iso_code" => "KN" ],
            [ "name" => "Saint Lucia", "iso_code" => "LC" ],
            [ "name" => "Saint Vincentnd the Grenadines", "iso_code" => "VC" ],
            [ "name" => "Samoa", "iso_code" => "WS" ],
            [ "name" => "San Marino", "iso_code" => "SM" ],
            [ "name" => "Sao Tomend Principe", "iso_code" => "ST" ],
            [ "name" => "Saudi Arabia", "iso_code" => "SA" ],
            [ "name" => "Senegal", "iso_code" => "SN" ],
            [ "name" => "Serbia", "iso_code" => "RS" ],
            [ "name" => "Seychelles", "iso_code" => "SC" ],
            [ "name" => "Sierra Leone", "iso_code" => "SL" ],
            [ "name" => "Singapore", "iso_code" => "SG" ],
            [ "name" => "Slovakia", "iso_code" => "SK" ],
            [ "name" => "Slovenia", "iso_code" => "SI" ],
            [ "name" => "Solomon Islands", "iso_code" => "SB" ],
            [ "name" => "Somalia", "iso_code" => "SO" ],
            [ "name" => "South Africa", "iso_code" => "ZA" ],
            [ "name" => "South Korea", "iso_code" => "KR" ],
            [ "name" => "South Sudan", "iso_code" => "SS" ],
            [ "name" => "Spain", "iso_code" => "ES" ],
            [ "name" => "Sri Lanka", "iso_code" => "LK" ],
            [ "name" => "Sudan", "iso_code" => "SD" ],
            [ "name" => "Suriname", "iso_code" => "SR" ],
            [ "name" => "Sweden", "iso_code" => "SE" ],
            [ "name" => "Switzerland", "iso_code" => "CH" ],
            [ "name" => "Syria", "iso_code" => "SY" ],
            [ "name" => "Taiwan", "iso_code" => "TW" ],
            [ "name" => "Tajikistan", "iso_code" => "TJ" ],
            [ "name" => "Tanzania", "iso_code" => "TZ" ],
            [ "name" => "Thailand", "iso_code" => "TH" ],
            [ "name" => "Timor-Leste", "iso_code" => "TL" ],
            [ "name" => "Togo", "iso_code" => "TG" ],
            [ "name" => "Tonga", "iso_code" => "TO" ],
            [ "name" => "Trinidad and obago", "iso_code" => "TT" ],
            [ "name" => "Tunisia", "iso_code" => "TN" ],
            [ "name" => "Turkey", "iso_code" => "TR" ],
            [ "name" => "Turkmenistan", "iso_code" => "TM" ],
            [ "name" => "Tuvalu", "iso_code" => "TV" ],
            [ "name" => "Uganda", "iso_code" => "UG" ],
            [ "name" => "Ukraine", "iso_code" => "UA" ],
            [ "name" => "United Arab mirates", "iso_code" => "AE" ],
            [ "name" => "United Kingdom", "iso_code" => "GB" ],
            [ "name" => "United States", "iso_code" => "US" ],
            [ "name" => "Uruguay", "iso_code" => "UY" ],
            [ "name" => "Uzbekistan", "iso_code" => "UZ" ],
            [ "name" => "Vanuatu", "iso_code" => "VU" ],
            [ "name" => "Vatican City", "iso_code" => "VA" ],
            [ "name" => "Venezuela", "iso_code" => "VE" ],
            [ "name" => "Vietnam", "iso_code" => "VN" ],
            [ "name" => "Yemen", "iso_code" => "YE" ],
            [ "name" => "Zambia", "iso_code" => "ZM" ],
            [ "name" => "Zimbabwe", "iso_code" => "ZW"]
        ];

        foreach ($countries as $key => $country) {
            Country::create($country);
        }

        $cities = [
            [ "country_id" => 1, "name" => "Kabul" ],
            [ "country_id" => 1, "name" => "Kandahar" ],
            [ "country_id" => 1, "name" => "Herat" ],
            [ "country_id" => 2, "name" => "Tirana" ],
            [ "country_id" => 2, "name" => "Durrës" ],
            [ "country_id" => 2, "name" => "Vlorë" ],
            [ "country_id" => 3, "name" => "Algiers" ],
            [ "country_id" => 3, "name" => "Oran" ],
            [ "country_id" => 3, "name" => "Constantine" ],
            [ "country_id" => 4, "name" => "Andorra la Vella" ],
            [ "country_id" => 5, "name" => "Luanda" ],
            [ "country_id" => 5, "name" => "N'dalatando" ],
            [ "country_id" => 5, "name" => "Huambo" ],
            [ "country_id" => 6, "name" => "Buenos Aires" ],
            [ "country_id" => 6, "name" => "Córdoba" ],
            [ "country_id" => 6, "name" => "Rosario" ],
            [ "country_id" => 7, "name" => "Yerevan" ],
            [ "country_id" => 7, "name" => "Gyumri" ],
            [ "country_id" => 7, "name" => "Vanadzor" ],
            [ "country_id" => 8, "name" => "Sydney" ],
            [ "country_id" => 8, "name" => "Melbourne" ],
            [ "country_id" => 8, "name" => "Brisbane" ],
            [ "country_id" => 9, "name" => "Vienna" ],
            [ "country_id" => 9, "name" => "Graz" ],
            [ "country_id" => 9, "name" => "Linz" ],
            [ "country_id" => 10, "name" => "Baku" ],
            [ "country_id" => 10, "name" => "Ganja" ],
            [ "country_id" => 10, "name" => "Sumqayit" ],
            [ "country_id" => 11, "name" => "Nassau" ],
            [ "country_id" => 12, "name" => "Manama" ],
            [ "country_id" => 13, "name" => "Dhaka" ],
            [ "country_id" => 13, "name" => "Chittagong" ],
            [ "country_id" => 13, "name" => "Khulna" ],
            [ "country_id" => 14, "name" => "Bridgetown" ],
            [ "country_id" => 15, "name" => "Minsk" ],
            [ "country_id" => 16, "name" => "Brussels" ],
            [ "country_id" => 16, "name" => "Antwerp" ],
            [ "country_id" => 16, "name" => "Ghent" ],
            [ "country_id" => 17, "name" => "Belmopan" ],
            [ "country_id" => 18, "name" => "Porto-Novo" ],
            [ "country_id" => 19, "name" => "Thimphu" ],
            [ "country_id" => 20, "name" => "Sucre" ],
            [ "country_id" => 21, "name" => "Sarajevo" ],
            [ "country_id" => 22, "name" => "Gaborone" ],
            [ "country_id" => 23, "name" => "Brasília" ],
            [ "country_id" => 24, "name" => "Bandar Seri Begawan" ],
            [ "country_id" => 25, "name" => "Sofia" ],
            [ "country_id" => 26, "name" => "Ouagadougou" ],
            [ "country_id" => 27, "name" => "Gitega" ],
            [ "country_id" => 28, "name" => "Praia" ],
            [ "country_id" => 29, "name" => "Phnom Penh" ],
            [ "country_id" => 30, "name" => "Yaoundé" ],
            [ "country_id" => 31, "name" => "Toronto" ],
            [ "country_id" => 31, "name" => "Vancouver" ],
            [ "country_id" => 31, "name" => "Montreal" ],
            [ "country_id" => 32, "name" => "N'Djamena" ],
            [ "country_id" => 32, "name" => "Moundou" ],
            [ "country_id" => 32, "name" => "Sarh" ],
            [ "country_id" => 33, "name" => "Santiago" ],
            [ "country_id" => 33, "name" => "Valparaíso" ],
            [ "country_id" => 33, "name" => "Concepción" ],
            [ "country_id" => 34, "name" => "Beijing" ],
            [ "country_id" => 34, "name" => "Shanghai" ],
            [ "country_id" => 34, "name" => "Chongqing" ],
            [ "country_id" => 35, "name" => "Bogotá" ],
            [ "country_id" => 35, "name" => "Medellín" ],
            [ "country_id" => 35, "name" => "Cali"],
            // Add more cities for other countries...
            [ "country_id" => 36, "name" => "Zagreb" ],
            [ "country_id" => 36, "name" => "Split" ],
            [ "country_id" => 36, "name" => "Dubrovnik" ],
            [ "country_id" => 37, "name" => "Havana" ],
            [ "country_id" => 37, "name" => "Santiago de Cuba" ],
            [ "country_id" => 37, "name" => "Camagüey" ],
            [ "country_id" => 38, "name" => "Nicosia" ],
            [ "country_id" => 38, "name" => "Limassol" ],
            [ "country_id" => 38, "name" => "Larnaca" ],
            [ "country_id" => 39, "name" => "Prague" ],
            [ "country_id" => 39, "name" => "Brno" ],
            [ "country_id" => 39, "name" => "Ostrava" ],
            [ "country_id" => 40, "name" => "Copenhagen" ],
            [ "country_id" => 40, "name" => "Aarhus" ],
            [ "country_id" => 40, "name" => "Odense" ],
            [ "country_id" => 41, "name" => "Djibouti City" ],
            [ "country_id" => 42, "name" => "Roseau" ],
            [ "country_id" => 43, "name" => "Santo Domingo" ],
            [ "country_id" => 43, "name" => "Santiago de los Caballeros" ],
            [ "country_id" => 44, "name" => "Quito" ],
            [ "country_id" => 44, "name" => "Guayaquil" ],
            [ "country_id" => 45, "name" => "Cairo" ],
            [ "country_id" => 45, "name" => "Alexandria" ],
            [ "country_id" => 45, "name" => "Giza" ],
            [ "country_id" => 46, "name" => "San Salvador" ],
            [ "country_id" => 47, "name" => "Malabo" ],
            [ "country_id" => 48, "name" => "Asmara" ],
            [ "country_id" => 49, "name" => "Tallinn" ],
            [ "country_id" => 49, "name" => "Tartu" ],
            [ "country_id" => 50, "name" => "Addis Ababa" ],
            [ "country_id" => 50, "name" => "Dire Dawa" ],
            [ "country_id" => 51, "name" => "Suva" ],
            [ "country_id" => 52, "name" => "Helsinki" ],
            [ "country_id" => 52, "name" => "Espoo" ],
            [ "country_id" => 52, "name" => "Tampere"],
            [ "country_id" => 53, "name" => "Paris" ],
            [ "country_id" => 53, "name" => "Marseille" ],
            [ "country_id" => 53, "name" => "Lyon" ],
            [ "country_id" => 54, "name" => "Berlin" ],
            [ "country_id" => 54, "name" => "Hamburg" ],
            [ "country_id" => 54, "name" => "Munich" ],
            [ "country_id" => 55, "name" => "Athens" ],
            [ "country_id" => 55, "name" => "Thessaloniki" ],
            [ "country_id" => 56, "name" => "Budapest" ],
            [ "country_id" => 57, "name" => "Reykjavík" ],
            [ "country_id" => 58, "name" => "New Delhi" ],
            [ "country_id" => 58, "name" => "Mumbai" ],
            [ "country_id" => 58, "name" => "Bangalore" ],
            [ "country_id" => 59, "name" => "Jakarta" ],
            [ "country_id" => 59, "name" => "Surabaya" ],
            [ "country_id" => 60, "name" => "Tehran" ],
            [ "country_id" => 60, "name" => "Mashhad" ],
            [ "country_id" => 61, "name" => "Baghdad" ],
            [ "country_id" => 61, "name" => "Basra" ],
            [ "country_id" => 62, "name" => "Dublin" ],
            [ "country_id" => 63, "name" => "Tel Aviv" ],
            [ "country_id" => 63, "name" => "Jerusalem" ],
            [ "country_id" => 64, "name" => "Rome" ],
            [ "country_id" => 64, "name" => "Milan" ],
            [ "country_id" => 65, "name" => "Tokyo" ],
            [ "country_id" => 65, "name" => "Yokohama" ],
            [ "country_id" => 66, "name" => "Amman" ],
            [ "country_id" => 67, "name" => "Nairobi" ],
            [ "country_id" => 68, "name" => "Astana" ],
            [ "country_id" => 68, "name" => "Almaty" ],
            [ "country_id" => 69, "name" => "Kuala Lumpur" ],
            [ "country_id" => 69, "name" => "George Town" ],
            [ "country_id" => 70, "name" => "Male" ],
            [ "country_id" => 71, "name" => "Valletta" ],
            [ "country_id" => 72, "name" => "Mexico City" ],
            [ "country_id" => 72, "name" => "Guadalajara" ],
            [ "country_id" => 72, "name" => "Monterrey"],
            [ "country_id" => 73, "name" => "Ulaanbaatar" ],
            [ "country_id" => 74, "name" => "Podgorica" ],
            [ "country_id" => 75, "name" => "Rabat" ],
            [ "country_id" => 75, "name" => "Casablanca" ],
            [ "country_id" => 76, "name" => "Maputo" ],
            [ "country_id" => 77, "name" => "Naypyidaw" ],
            [ "country_id" => 77, "name" => "Yangon" ],
            [ "country_id" => 78, "name" => "Windhoek" ],
            [ "country_id" => 79, "name" => "Kathmandu" ],
            [ "country_id" => 79, "name" => "Pokhara" ],
            [ "country_id" => 80, "name" => "Amsterdam" ],
            [ "country_id" => 80, "name" => "Rotterdam" ],
            [ "country_id" => 81, "name" => "Wellington" ],
            [ "country_id" => 82, "name" => "Managua" ],
            [ "country_id" => 83, "name" => "Niamey" ],
            [ "country_id" => 84, "name" => "Abuja" ],
            [ "country_id" => 84, "name" => "Lagos" ],
            [ "country_id" => 85, "name" => "Oslo" ],
            [ "country_id" => 86, "name" => "Muscat" ],
            [ "country_id" => 87, "name" => "Islamabad" ],
            [ "country_id" => 87, "name" => "Karachi" ],
            [ "country_id" => 87, "name" => "Lahore" ],
            [ "country_id" => 88, "name" => "Manila" ],
            [ "country_id" => 89, "name" => "Warsaw" ],
            [ "country_id" => 89, "name" => "Kraków" ],
            [ "country_id" => 90, "name" => "Lisbon" ],
            [ "country_id" => 90, "name" => "Porto" ],
            [ "country_id" => 91, "name" => "San Juan" ],
            [ "country_id" => 92, "name" => "Doha" ],
            [ "country_id" => 93, "name" => "Bucharest" ],
            [ "country_id" => 93, "name" => "Cluj-Napoca" ],
            [ "country_id" => 94, "name" => "Moscow" ],
            [ "country_id" => 94, "name" => "Saint Petersburg" ],
            [ "country_id" => 94, "name" => "Novosibirsk" ],
            [ "country_id" => 95, "name" => "Kigali" ],
            [ "country_id" => 96, "name" => "Riyadh" ],
            [ "country_id" => 97, "name" => "Dakar" ],
            [ "country_id" => 98, "name" => "Belgrade" ],
            [ "country_id" => 98, "name" => "Novi Sad" ],
            [ "country_id" => 99, "name" => "Freetown" ],
            [ "country_id" => 100, "name" => "Singapore" ],
            [ "country_id" => 101, "name" => "Bratislava" ],
            [ "country_id" => 102, "name" => "Ljubljana" ],
            [ "country_id" => 103, "name" => "Honiara" ],
            [ "country_id" => 104, "name" => "Mogadishu" ],
            [ "country_id" => 105, "name" => "Pretoria" ],
            [ "country_id" => 105, "name" => "Johannesburg" ],
            [ "country_id" => 105, "name" => "Cape Town" ],
            [ "country_id" => 106, "name" => "Seoul" ],
            [ "country_id" => 106, "name" => "Busan" ],
            [ "country_id" => 106, "name" => "Incheon" ],
            [ "country_id" => 107, "name" => "Madrid" ],
            [ "country_id" => 107, "name" => "Barcelona" ],
            [ "country_id" => 108, "name" => "Colombo" ],
            [ "country_id" => 109, "name" => "Khartoum" ],
            [ "country_id" => 110, "name" => "Paramaribo" ],
            [ "country_id" => 111, "name" => "Stockholm" ],
            [ "country_id" => 112, "name" => "Bern" ],
            [ "country_id" => 113, "name" => "Damascus" ],
            [ "country_id" => 114, "name" => "Taipei" ],
            [ "country_id" => 114, "name" => "Kaohsiung" ],
            [ "country_id" => 115, "name" => "Dushanbe" ],
            [ "country_id" => 116, "name" => "Dodoma" ],
            [ "country_id" => 116, "name" => "Dar es Salaam" ],
            [ "country_id" => 117, "name" => "Bangkok" ],
            [ "country_id" => 117, "name" => "Chiang Mai" ],
            [ "country_id" => 118, "name" => "Lomé" ],
            [ "country_id" => 119, "name" => "Port of Spain" ],
            [ "country_id" => 120, "name" => "Tunis" ],
            [ "country_id" => 121, "name" => "Ankara" ],
            [ "country_id" => 121, "name" => "Istanbul" ],
            [ "country_id" => 121, "name" => "Izmir" ],
            [ "country_id" => 122, "name" => "Ashgabat" ],
            [ "country_id" => 123, "name" => "Funafuti" ],
            [ "country_id" => 124, "name" => "Kampala" ],
            [ "country_id" => 125, "name" => "Kiev" ],
            [ "country_id" => 125, "name" => "Kharkiv" ],
            [ "country_id" => 125, "name" => "Odesa" ],
            [ "country_id" => 126, "name" => "Abu Dhabi" ],
            [ "country_id" => 126, "name" => "Dubai" ],
            [ "country_id" => 127, "name" => "London" ],
            [ "country_id" => 127, "name" => "Manchester" ],
            [ "country_id" => 128, "name" => "Washington, D.C." ],
            [ "country_id" => 128, "name" => "New York City" ],
            [ "country_id" => 128, "name" => "Los Angeles" ],
            [ "country_id" => 129, "name" => "Montevideo" ],
            [ "country_id" => 130, "name" => "Tashkent" ],
            [ "country_id" => 131, "name" => "Port Vila" ],
            [ "country_id" => 132, "name" => "Vatican City" ],
            [ "country_id" => 133, "name" => "Caracas" ],
            [ "country_id" => 133, "name" => "Maracaibo" ],
            [ "country_id" => 134, "name" => "Hanoi" ],
            [ "country_id" => 134, "name" => "Ho Chi Minh City" ],
            [ "country_id" => 135, "name" => "Sana'a" ],
            [ "country_id" => 136, "name" => "Lusaka" ],
            [ "country_id" => 137, "name" => "Harare"],
            [ "country_id" => 138, "name" => "Kigali" ],
            [ "country_id" => 139, "name" => "Vientiane" ],
            [ "country_id" => 140, "name" => "Mogadishu" ],
            [ "country_id" => 141, "name" => "Naypyidaw" ],
            [ "country_id" => 142, "name" => "Male" ],
            [ "country_id" => 143, "name" => "Moroni" ],
            [ "country_id" => 144, "name" => "Juba" ],
            [ "country_id" => 145, "name" => "Gaborone" ],
            [ "country_id" => 146, "name" => "Port Moresby" ],
            [ "country_id" => 147, "name" => "Apia" ],
            [ "country_id" => 148, "name" => "Suva" ],
            [ "country_id" => 149, "name" => "Palikir" ],
            [ "country_id" => 150, "name" => "Honiara" ],
            [ "country_id" => 151, "name" => "Tarawa" ],
            [ "country_id" => 152, "name" => "Nuku'alofa" ],
            [ "country_id" => 153, "name" => "Kingstown" ],
            [ "country_id" => 154, "name" => "Saint George's" ],
            [ "country_id" => 155, "name" => "Basseterre" ],
            [ "country_id" => 156, "name" => "Castries" ],
            [ "country_id" => 157, "name" => "Saint John's" ],
            [ "country_id" => 158, "name" => "Port Louis" ],
            [ "country_id" => 159, "name" => "Nassau" ],
            [ "country_id" => 160, "name" => "Saint-Pierre" ],
            [ "country_id" => 161, "name" => "Road Town" ],
            [ "country_id" => 162, "name" => "Cockburn Town" ],
            [ "country_id" => 163, "name" => "Cayenne" ],
            [ "country_id" => 164, "name" => "Stanley"],
            [ "country_id" => 165, "name" => "Georgetown" ],
            [ "country_id" => 166, "name" => "Nuuk" ],
            [ "country_id" => 167, "name" => "Longyearbyen" ],
            [ "country_id" => 168, "name" => "Mariehamn" ],
            [ "country_id" => 169, "name" => "Oranjestad" ],
            [ "country_id" => 170, "name" => "Gustavia" ],
            [ "country_id" => 171, "name" => "The Valley" ],
            [ "country_id" => 172, "name" => "Cockburn Town" ],
            [ "country_id" => 173, "name" => "Hamilton" ],
            [ "country_id" => 174, "name" => "Willemstad" ],
            [ "country_id" => 175, "name" => "Philipsburg" ],
            [ "country_id" => 176, "name" => "Saint John's" ],
            [ "country_id" => 177, "name" => "Bridgetown" ],
            [ "country_id" => 178, "name" => "Basseterre" ],
            [ "country_id" => 179, "name" => "Kingstown" ],
            [ "country_id" => 180, "name" => "Castries" ],
            [ "country_id" => 181, "name" => "Roseau" ],
            [ "country_id" => 182, "name" => "Fort-de-France" ],
            [ "country_id" => 183, "name" => "Saint-Pierre" ],
            [ "country_id" => 184, "name" => "Basseterre" ],
            [ "country_id" => 185, "name" => "Saint John's" ],
            [ "country_id" => 186, "name" => "Bridgetown" ],
            [ "country_id" => 187, "name" => "Basseterre" ],
            [ "country_id" => 188, "name" => "Castries" ],
            [ "country_id" => 189, "name" => "Port Louis" ],
            [ "country_id" => 190, "name" => "Port Moresby" ],
            [ "country_id" => 191, "name" => "Ngerulmud" ],
            [ "country_id" => 192, "name" => "Palikir" ],
            [ "country_id" => 193, "name" => "Apia" ],
            [ "country_id" => 194, "name" => "Kingstown" ],
        ];

        foreach ($cities as $key => $city) {
            City::create($city);
        }
    }
}
